apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-devopsnotes-deployment
  namespace: blog-prod
  labels:
    app: blog-devopsnotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-devopsnotes
  template:
    metadata:
      labels:
        app: blog-devopsnotes
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: blog-backend
        image: ghcr.io/kamouloxpelvis/blog-devopsnotes-backend:${{ github.sha }}
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DEBUG
          value: "app:*"
        envFrom:
        - secretRef:
            name: blog-secrets
      - name: blog-frontend
        image: ghcr.io/kamouloxpelvis/blog-devopsnotes-frontend:${{ github.sha }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80