name: DevOpsNotes Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/kamouloxpelvis/blog-devopsnotes

jobs:

  # =========================================================
  # BUILD & PUSH
  # =========================================================

  build:
    name: Build & Push Docker images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -------------------------------------------------------
      # Backend
      # -------------------------------------------------------

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-backend:latest
            ${{ env.IMAGE_PREFIX }}-backend:${{ github.sha }}

      # -------------------------------------------------------
      # Frontend
      # -------------------------------------------------------

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-frontend:latest
            ${{ env.IMAGE_PREFIX }}-frontend:${{ github.sha }}
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}

  # =========================================================
  # DEPLOY K3S
  # =========================================================

  deploy:
    name: Deploy to K3s
    needs: build
    runs-on: self-hosted

    steps:

      - name: Verify Kubernetes access
        env:
          KUBECONFIG: /home/kamal/.kube/config
        run: |
          set -e

          echo "🔍 Checking Kubernetes access..."

          kubectl config current-context
          kubectl get nodes

      - name: Deploy
        env:
          IMAGE_TAG: ${{ github.sha }}
          KUBECONFIG: /home/kamal/.kube/config
        run: |
          set -e

          echo "🚀 Deploying DevOpsNotes ${IMAGE_TAG}"

          kubectl -n blog-prod set image deployment/blog-devopsnotes-deployment \
            blog-backend=ghcr.io/kamouloxpelvis/blog-devopsnotes-backend:${IMAGE_TAG} \
            blog-frontend=ghcr.io/kamouloxpelvis/blog-devopsnotes-frontend:${IMAGE_TAG}

          kubectl -n blog-prod rollout status \
            deployment/blog-devopsnotes-deployment \
            --timeout=300s

          echo "✅ DevOpsNotes deployment successful"